name: 'Call GCP'

on:
  workflow_dispatch:

jobs:
  call-gcp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0.4.3
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.SA_EMAIL }}
      
    - name: Run gcloud
      run: gcloud kms keys describe --keyring=for-e2e-test
