name: 'Call GCP'

on:
  workflow_dispatch:

jobs:
  call-gcp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0.4.3
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.SA_EMAIL }}
      
    - name: Run gcloud
      run: gcloud kms keys versions get-public-key 1 \
            --key secp256k1-key \
            --keyring for-e2e-test \
            --location global \
            --output-file public-key.pub
    - name: Show public-key.pub
      run: cat public-key.pub
